name: product_services
services:
  leitsystem-api:
    container_name: room_api
    build:
      context: .
      dockerfile: leitsystem-api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=http://0.0.0.0:8080
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - docker_sqlserver

  docker_sqlserver:
    container_name: docker_sqlserver
    build:
      context: .
      dockerfile: leitsystem-api/db.Dockerfile
    ports:
      - "1433:1433"